name: Check Arduino

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

  workflow_dispatch:

concurrency:
  group: arduino-check
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: arduino/arduino-lint-action
        uses: arduino/arduino-lint-action@v2.0.0
        with:
          #path:
          #version:
          compliance: strict
          library-manager: update
          project-type: all
          recursive: true
          #report-file: ${{ env.REPORT_FILE_PATH }}
          #verbose: true
          #official: false
          #token: ${{ github.token }}

  compile:
    strategy:
      fail-fast: false

      matrix:
        boards: [arduino-uno, arduino-mega, arduino-leonardo]

        include:
          - boards: arduino-uno
            arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:uno"
            serial-enabled: true

          - boards: arduino-mega
            arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:mega"
            serial-enabled: true

          - boards: arduino-leonardo
            arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:leonardo"
            serial-enabled: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Zip
        uses: montudor/action-zip@v0.1.1

      - name: Zip Ultrasonic.zip
        run: |
          # Create library folder structure
          mkdir -p MinimalUltrasonic

          # Copy library files (exclude docs, CI config, git metadata, node_modules)
          rsync -a --exclude='.github' --exclude='docs' --exclude='.git' --exclude='node_modules' --exclude='MinimalUltrasonic' ./ MinimalUltrasonic/

          # Create zip with the library folder
          zip -qq -r ultrasonic.zip MinimalUltrasonic
        working-directory: ${{ github.workspace }}

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2.0.0

      - name: Install Arduino Platform
        run: |
          arduino-cli core download ${{ matrix.arduino-platform }}
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}

      #This is needed because we are using --zip-path to install a library
      - name: Enables unsafe install
        run: |
          arduino-cli config init 
          arduino-cli config set library.enable_unsafe_install true

      - name: Install Ultrasonic.h
        run: arduino-cli lib install --zip-path ./ultrasonic.zip

      - name: Compile Sketch `basic.ino`
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./examples/basic

      - name: Compile Sketch `advanced.ino`
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./examples/advanced

      - name: Compile Sketch `all-units.ino`
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./examples/all-units

      - name: Compile Sketch `multiple-sensors.ino`
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./examples/multiple-sensors

      - name: Compile Sketch `timeout.ino`
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./examples/timeout
